on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build VSClone based on patched VSCode Web artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build vscode-web with proper caching
      - name: Cache Docker layers for VSCode Web
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-vscode-web-${{ hashFiles('external/vscode/**') }}
          restore-keys: |
            ${{ runner.os }}-vscode-web-

      - name: Build VSCode Web
        uses: docker/build-push-action@v5
        with:
          context: external/vscode/patched
          push: false
          load: true
          tags: vscode-web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - working-directory: ./external/vscode
        run: |
          rm -rf ./dist && mkdir -p ./dist/vscode
          docker run --rm -v $(pwd)/dist/vscode:/dist vscode-web
          zip -r ../../assets/vscode-web.zip ./dist

      - name: Build project archive
        env:
          DIST_OS: windows linux
          DIST_ARCH: arm64 amd64
        run: make archive
      
      - name: Put VSCode Web asset in dist artifacts
        run: cp -r ./assets/vscode-web.zip ./dist

      - name: Clean non-zip files in dist/
        run: find dist/ -type f ! -name '*.zip' -exec rm -f {} +

      - uses: actions/upload-artifact@v4
        with:
          name: vsclone-dist
          path: dist/