on:
  push:
    branches:
      - main
jobs:
  detect-vscode-changes:
    name: Detect VSCode changes
    runs-on: ubuntu-latest
    outputs:
      vscode-changed: ${{ steps.changes.outputs.vscode }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            vscode:
              - 'external/vscode/**'
  
  build-vscode:
    name: Build patched VSCode Web artifact
    needs: detect-vscode-changes
    if: needs.detect-vscode-changes.outputs.vscode-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build VSCode Web
        uses: docker/build-push-action@v5
        with:
          context: external/vscode/patched
          push: true
          load: true
          tags: ghcr.io/${{ github.repository }}:vscode-web


  setup-vscode-web:
    name: Setup VSCode Web artifact
    needs: [detect-vscode-changes, build-vscode]
    if: always() && needs.detect-vscode-changes.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: |
          rm -rf ./vscode-web
          docker run --rm -v $(pwd)/vscode-web:/dist ghcr.io/${{ github.repository }}:vscode-web
      
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-web
          path: vscode-web

  build-windows:
    name: Build for Windows (arm64, amd64)
    needs: setup-vscode-web
    if: always() && needs.setup-vscode-web.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DIST_OS: windows
      DIST_ARCH: arm64 amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - uses: actions/download-artifact@v4
        with:
          name: vscode-web
          path: tmp
      - run: |
          cd tmp && zip -r ../assets/vscode-web.zip .

      - name: Build project
        run: make archive

      - uses: actions/upload-artifact@v4
        with:
          name: vsclone-windows
          path: dist/

  build-linux:
    name: Build for Linux (arm64, amd64)
    needs: setup-vscode-web
    if: always() && needs.setup-vscode-web.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DIST_OS: linux
      DIST_ARCH: arm64 amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - uses: actions/download-artifact@v4
        with:
          name: vscode-web
          path: tmp
      - run: |
          cd tmp && zip -r ../assets/vscode-web.zip .

      - name: Build project
        run: make archive

      - uses: actions/upload-artifact@v4
        with:
          name: vsclone-linux
          path: dist/
  
  build-darwin-arm64:
    name: Build for Darwin (arm64)
    needs: setup-vscode-web
    if: always() && needs.setup-vscode-web.result == 'success'
    runs-on: macos-14
    permissions:
      contents: write
    env:
      DIST_OS: darwin
      DIST_ARCH: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - uses: actions/download-artifact@v4
        with:
          name: vscode-web
          path: tmp
      - run: |
          cd tmp && zip -r ../assets/vscode-web.zip .

      - name: Build project
        run: make archive

      - uses: actions/upload-artifact@v4
        with:
          name: vsclone-darwin-arm64
          path: dist/

  build-darwin-amd64:
    name: Build for Darwin (amd64)
    needs: setup-vscode-web
    if: always() && needs.setup-vscode-web.result == 'success'
    runs-on: macos-13
    permissions:
      contents: write
    env:
      DIST_OS: darwin
      DIST_ARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - uses: actions/download-artifact@v4
        with:
          name: vscode-web
          path: tmp
      - run: |
          cd tmp && zip -r ../assets/vscode-web.zip .

      - name: Build project
        run: make archive

      - uses: actions/upload-artifact@v4
        with:
          name: vsclone-darwin-amd64
          path: dist/
