name: Build VSClone
on:
  push:
    branches:
      - main

jobs:
  vscode-web:
    name: VSCode Web
    uses: progrium/github-workflows/.github/workflows/vscode-web.yml@main
    permissions:
      contents: read
      packages: write
    with:
      artifact-name: vscode-web
      path: external/vscode-web

  build:
    name: Build
    needs: vscode-web
    uses: progrium/github-workflows/.github/workflows/golang-cli-build.yml@main
    with:
      bin-name: vsclone
      go-version: '1.23.1'
      needs-artifact: vscode-web
      pre-build-script: |
        cd _artifact && zip -r ../assets/vscode-web.zip .
    secrets: inherit
