name: Build VSClone
on:
  push:
    branches:
      - main

jobs:
  detect-vscode-changes:
    name: Detect VSCode changes
    runs-on: ubuntu-latest
    outputs:
      vscode-changed: ${{ steps.changes.outputs.vscode }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            vscode:
              - 'external/vscode/**'
  
  build-vscode:
    name: Build patched VSCode Web
    needs: detect-vscode-changes
    if: needs.detect-vscode-changes.outputs.vscode-changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build VSCode Web
        uses: docker/build-push-action@v5
        with:
          context: external/vscode/patched
          push: true
          tags: ghcr.io/${{ github.repository }}:vscode-web


  setup-vscode-web:
    name: Prepare VSCode artifact
    needs: [detect-vscode-changes, build-vscode]
    if: always() && needs.detect-vscode-changes.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: |
          rm -rf ./vscode-web
          mkdir -p ./vscode-web/vscode
          docker run --rm -v $(pwd)/vscode-web/vscode:/dist ghcr.io/${{ github.repository }}:vscode-web
      
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-web
          path: vscode-web

  build:
    name: Build
    needs: setup-vscode-web
    if: always() && needs.setup-vscode-web.result == 'success'
    uses: progrium/github-workflows/.github/workflows/golang-cli-build.yml@main
    with:
      bin-name: vsclone
      go-version: '1.23.1'
      needs-artifact: vscode-web
      pre-build-script: |
        cd _artifact && zip -r ../assets/vscode-web.zip .
    secrets: inherit
